### ISSUE TITLE
Error: Cannot find module './index.c0ba7d56.js'

### ISSUE THREAD

**Issue by mtdvlpr** [caoxiemeihao/nuxt-electron#16]
Hi (again),

After solving #14, I'm faced with an even weird error. None of the nuxt generated scripts can be found when running a production build. Only entry.js.

Minimal reproduction repo: https://github.com/mtdvlpr/minimal-reproduction

Sorry to bother you again, but if you (or someone else) could figure this out, that'd be great!

**Comment by caoxiemeihao** [comment]
At present, you can add following options into you App.
It's will be integrate the next version.

```diff
{
+ app: {
+   buildAssetsDir: '/',
+ },
}
```

**Comment by mtdvlpr** [comment]
@caoxiemeihao, implementing this shows a bunch of other errors (see reproduction repo).

**Comment by mtdvlpr** [comment]
@caoxiemeihao any idea what's happening here?

**Comment by mtdvlpr** [comment]
Alright, thanks for the hard work!

**Comment by caoxiemeihao** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/26263658/226186713-4b025bf0-79b6-471b-8a0a-6760a3fb26c9.png">

`vue-router` uses dynamic import, which is the cause of the BUG, and I'm still looking for a way to disable it.

https://github.com/electron-vite/electron-vite-vue/issues?q=is%3Aissue+router#issuecomment-1375175289

**Comment by mtdvlpr** [comment]
Is there any workaround for this? I need to be able to build my app for production...

**Comment by caoxiemeihao** [comment]
Upgrade `vite-plugin-electron-renderer` to `v0.13.7` 😅
https://github.com/electron-vite/vite-plugin-electron-renderer/pull/45

**Comment by mtdvlpr** [comment]
The minimal reproduction works! On my real project I'm getting a memory leak:
`FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`
I'm using Node.js v18.15

**Comment by caoxiemeihao** [comment]
How I reproduce it?

**Comment by mtdvlpr** [comment]
I fixed it using `cross-env NODE_OPTIONS=--max-old-space-size=4096`

**Comment by mtdvlpr** [comment]
Now I've run into the next issue: the styles aren't being imported in production (see https://github.com/mtdvlpr/minimal-reproduction).

I'm using Vuetify and the styles.css is generated, but it's not being referenced in the generated html files for some reason...

**Comment by mtdvlpr** [comment]
And in development mode (`yarn run dev`) I get the following error:
```javascript
Uncaught TypeError: Cannot set property close of #<Object> which has only a getter
    at node_modules/graceful-fs/graceful-fs.js (graceful-fs.js:52:6)
    at __require2 (chunk-OROXOI2D.js?v=7dae7f69:16:50)
    at node_modules/fs-extra/lib/fs/index.js (index.js:5:12)
    at __require2 (chunk-OROXOI2D.js?v=7dae7f69:16:50)
    at node_modules/fs-extra/lib/index.js (index.js:5:6)
    at __require2 (chunk-OROXOI2D.js?v=7dae7f69:16:50)
    at index.js:16:1
```

**Comment by mtdvlpr** [comment]
> Now I've run into the next issue on production build: the styles aren't being imported in production (see https://github.com/mtdvlpr/minimal-reproduction).
> 
> I'm using Vuetify and the styles.css is generated, but it's not being referenced in the generated html files for some reason...

@caoxiemeihao should I move this issue to `vite-plugin-electron-renderer`?

**Comment by caoxiemeihao** [comment]
I say this BUG, it from `esbuild` pre-bundle, I'm in try to resolve it now 👀

**Comment by caoxiemeihao** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/26263658/228397517-f05b6f89-391b-450b-9333-89430b0de5d5.png">

The code generated by `esbuild` will be wrapped `Object.defineProperty` and just provide `get` property, it can cnuse the BUG.
MDN - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Getter_only#examples
esbuild - https://github.com/evanw/esbuild/issues/587

But, we can  avoid the Vite's pre-bundle default behavior resolve it.

```ts
export default defineNuxtConfig({
  electron: {
    renderer: {
      resolve: {
        'fs-extra': () => ({ platform: 'node' }), // here
      },
    },
  },
});
```

**Comment by mtdvlpr** [comment]
In dev mode (see https://github.com/mtdvlpr/minimal-reproduction):

```javascript
[Vue warn]: Failed to resolve component: v-btn
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouteProvider key="/" routeProps= {Component: {…}, route: {…}} pageKey="/"  ... > 
  at <FragmentWrapper > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=2 > 
  at <NuxtRoot>
```

**Comment by caoxiemeihao** [comment]
A new to Nuxt? I'm a new to Nuxt and just read the `vuetify` docs, found it :)

https://vuetifyjs.com/en/getting-started/installation/#manual-steps

<img width="700" alt="image" src="https://user-images.githubusercontent.com/26263658/228713357-8aafacbb-6e74-4cf0-96a2-e2015e8b5693.png">

**Comment by mtdvlpr** [comment]
Sorry about that. Forgot the vite vuetify plugin. In production the styling is still gone...
![Screenshot from 2023-03-30 07-24-41](https://user-images.githubusercontent.com/46671786/228737772-580fed07-9d72-4304-831c-81bbe180627f.png)
![Screenshot from 2023-03-30 07-25-11](https://user-images.githubusercontent.com/46671786/228737826-2d533d7c-ec90-43cd-825c-6ab68bebc880.png)

**Comment by caoxiemeihao** [comment]
> In production the styling is still gone...the .css file is there

https://github.com/caoxiemeihao/nuxt-electron/blob/v0.4.5/examples/quick-start/nuxt.config.ts#L8-L13

**Comment by mtdvlpr** [comment]
@caoxiemeihao `cssCodeSplit: true` did the trick! I can finally build my application for production 🎉  

Thanks so much for all the hard work and effort!
