### ISSUE TITLE
 ERROR  [unhandledRejection] options.build is not iterable 

### ISSUE THREAD

**Issue by 171h** [caoxiemeihao/nuxt-electron#39]
when I update nuxt-electron from `0.4.5` to `0.6.0` or `0.5.0`, report errors

Nuxt project info:                                                                                                                                                                      09:21:17

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.3.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.6
- Builder:          vite
- User Config:      modules, electron
- Runtime Modules:  nuxt-electron@0.5.0
- Build Modules:    -
------------------------------

```
 ERROR  [unhandledRejection] options.build is not iterable                                                                                                                              09:19:31  

  at _listen (/G:/repo/test/test-nuxt-electron/node_modules/.pnpm/nuxt-electron@0.5.0_vite-plugin-electron-renderer@0.14.5_vite-plugin-electron@0.11.2/node_modules/nuxt-electron/dist/index.mjs:51:38)
  at listen (/G:/repo/test/test-nuxt-electron/node_modules/.pnpm/nuxt-electron@0.5.0_vite-plugin-electron-renderer@0.14.5_vite-plugin-electron@0.11.2/node_modules/nuxt-electron/dist/index.mjs:74:9)
  at /G:/repo/test/test-nuxt-electron/node_modules/.pnpm/hookable@5.5.3/node_modules/hookable/dist/index.mjs:48:66
  at /G:/repo/test/test-nuxt-electron/node_modules/.pnpm/hookable@5.5.3/node_modules/hookable/dist/index.mjs:48:56
  at async load (/G:/repo/test/test-nuxt-electron/node_modules/.pnpm/nuxi@3.6.5/node_modules/nuxi/dist/chunks/dev.mjs:217:9)
  at async Object.invoke (/G:/repo/test/test-nuxt-electron/node_modules/.pnpm/nuxi@3.6.5/node_modules/nuxi/dist/chunks/dev.mjs:249:5)
  at async _main (/G:/repo/test/test-nuxt-electron/node_modules/.pnpm/nuxi@3.6.5/node_modules/nuxi/dist/cli.mjs:49:20)

ℹ Vite client warmed up in 1462ms                                                                                                                                                      09:19:34
✔ Nitro built in 1881 ms               
```

**Comment by caoxiemeihao** [comment]
<img width="630" alt="image" src="https://github.com/caoxiemeihao/nuxt-electron/assets/26263658/356ab929-ac10-41a3-8dde-c05124a0194f">

Plase use `vite-plugin-electron` instead `vite-electron-plugin`, you can see the details for useage in the `v0.6.0` README.md
