### ISSUE TITLE
[BUG] 官方例子跑不动

### ISSUE THREAD

**Issue by InfernalAzazel** [caoxiemeihao/nuxt-electron#40]
![2023-07-31_13-23](https://github.com/caoxiemeihao/nuxt-electron/assets/40333954/4a6fbcc0-2d8f-47fe-98b9-4d8eda120c16)

异常:

```
/usr/bin/pnpm run build

> nuxt-electron-quick-start@0.0.0 build /work/code/github/nuxt-electron/examples/quick-start
> nuxi build --prerender && electron-builder

Nuxi 3.6.3                                                                                                                                               13:18:48
Nuxt 3.6.3 with Nitro 2.5.2                                                                                                                              13:18:48

 ERROR  Error while requiring module nuxt-electron: Error: Cannot find module '/work/code/github/nuxt-electron/examples/quick-start/nuxt-electron'       13:18:49
Require stack:
- /work/code/github/nuxt-electron/examples/quick-start/index.js


 ERROR  Cannot find module '/work/code/github/nuxt-electron/examples/quick-start/nuxt-electron'                                                          13:18:49
Require stack:
- /work/code/github/nuxt-electron/examples/quick-start/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
  at Function.resolve (node:internal/modules/cjs/helpers:114:19)
  at Function._resolve [as resolve] (/work/code/github/nuxt-electron/node_modules/.pnpm/jiti@1.19.1/node_modules/jiti/dist/jiti.js:1:250100)
  at resolveModule (/work/code/github/nuxt-electron/node_modules/.pnpm/@nuxt+kit@3.6.3/node_modules/@nuxt/kit/dist/index.mjs:2230:29)
  at requireModule (/work/code/github/nuxt-electron/node_modules/.pnpm/@nuxt+kit@3.6.3/node_modules/@nuxt/kit/dist/index.mjs:2240:24)
  at loadNuxtModuleInstance (/work/code/github/nuxt-electron/node_modules/.pnpm/@nuxt+kit@3.6.3/node_modules/@nuxt/kit/dist/index.mjs:2435:90)
  at async installModule (/work/code/github/nuxt-electron/node_modules/.pnpm/@nuxt+kit@3.6.3/node_modules/@nuxt/kit/dist/index.mjs:2408:47)
  at async initNuxt (/work/code/github/nuxt-electron/node_modules/.pnpm/nuxt@3.6.3_@types+node@20.4.2_typescript@5.1.6/node_modules/nuxt/dist/index.mjs:3237:7)
  at async loadNuxt (/work/code/github/nuxt-electron/node_modules/.pnpm/nuxt@3.6.3_@types+node@20.4.2_typescript@5.1.6/node_modules/nuxt/dist/index.mjs:3310:5)
  at async loadNuxt (/work/code/github/nuxt-electron/node_modules/.pnpm/@nuxt+kit@3.6.3/node_modules/@nuxt/kit/dist/index.mjs:2537:19)

```

**Comment by caoxiemeihao** [comment]
你把 `quick-start` 文件夹单独拿出来，然后 `npm i` 装依赖，然后 `npm run dev`。
在一起会很麻烦，不推荐这么使用。
