### ISSUE TITLE
無限循環刷新

### ISSUE THREAD

**Issue by naruko-hstk** [caoxiemeihao/nuxt-electron#90]
![image](https://github.com/user-attachments/assets/0d79f83a-086e-4307-860a-eec82d8d761f)
應該有人提過了

總之照著readme寫的方式進行設定後就這樣了
這是具體錯誤
```log
 ERROR  [unhandledRejection] write after end                                                                                                                                            6:31:21

  at _write (node:internal/streams/writable:487:11)
  at Writable.write (node:internal/streams/writable:508:10)
  at Sender.sendFrame (node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:56597:20)
  at Sender.close (node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:56258:12)
  at WebSocket.close (node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:57444:18)
  at Receiver.receiverOnConclude (node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:58291:18)
  at Receiver.emit (node:events:519:28)
  at Receiver.controlMessage (node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:55991:14)
  at Receiver.getData (node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:55810:12)
  at Receiver.startLoop (node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:55500:16)
```

**Comment by reitowo** [comment]
electron: {
  disableDefaultOptions: true,
}

will be a workaround.

**Comment by angelhdzdev** [comment]
> ```
> electron: {
>   disableDefaultOptions: true,
> }
> ```
> 
> will be a workaround.

This solves this apparently!!! https://github.com/caoxiemeihao/nuxt-electron/issues/94

Thanks!!! ❤️🤯🤝👏🎉
